# .travis.xml for use with EPICS Base ci-scripts
# (see: https://github.com/epics-base/ci-scripts)

language: cpp
compiler: gcc
dist: xenial

# Minimal set of packages needed to compile EPICS Base

cache:
  directories:
  - $HOME/.cache

env:
  global:
   - SETUP_PATH=.ci

addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl

install:
  - ./.ci/travis/prepare.sh

script:
  - ./.ci/travis/build.sh

# Build using default gcc for Base branches 7.0 and 3.15

jobs:
  include:
  - env: BASE=7.0

  - env: BASE=R3.15.7
